### ISSUE TITLE
HttpMethod no "DELETE"

### ISSUE THREAD

**Issue by portwatcher** [heroiclabs/nakama-common#105]
https://github.com/heroiclabs/nakama-common/blob/49493e301be4caa1b527aca8dc98a8c49e32c27c/index.d.ts#L2225

Is it missed or it is intended?
Can I use `'delete'` method in a `nk.httpRequest()`?

**Comment by zyro** [comment]
@portwatcher This is an oversight, `DELETE` should be allowed. We'll fix ahead of the next release, thanks for pointing this out!

**Comment by zyro** [comment]
Fixed on master and will be part of the next release. 👍

**Comment by portwatcher** [comment]
I've updated package but got error below, I'm not sure what's wrong. This maybe a user error, I may miss something. or this is related to go codes.

```
{"level":"error","ts":"2022-12-18T05:59:30.920Z","caller":"server/runtime_javascript_logger.go:94","msg":"Invalid method must be one of: 'get', 'post', 'put', 'patch'.","mid":"4cc92f85-c48d-489b-95ce-c5cc1f0bd6a7"}
```

<img width="848" alt="image" src="https://user-images.githubusercontent.com/2919533/208283995-69939d4c-246a-4a85-94f8-8db6929fd42b.png">
