### ISSUE TITLE
Wasm 

### ISSUE THREAD

**Issue by gedw99** [heroiclabs/nakama-common#120]
.lua, .so, and .js Are the current runtime authoring options.

Wazero runs wasm with no cgo and is V1 now. The no cgo is great be Ayse builds are easy.

it will allow devs to write their logic in any language that compiles to wasm . Rust, go. Typescript, python, c, c#, and many more.

**Comment by novabyte** [comment]
@gedw99 I've been tracking what it could look like to support a WASM runtime and allow game teams to write their server code in whichever language supports WASM as a compiler target. 

What's unclear at the moment is how to maintain the set of necessary interfaces/headers/typedefs for each of the languages that compile to WASM? How do others maintain these stubs?

**Comment by joshua-mng** [comment]
This would be a game changer, hope to see this implemented in nakama soon.

**Comment by Waffleophagus** [comment]
Another random idea, could you just expose the functions of Nakama as an API? WASM would be amazing as it would enable any number of languages, but implementing an interface to allow Nakama to just call out to a container in the same cluster and/or on the same network. You could let them communicate and that way remove any limitations to people using your services.

**Comment by MWFIAE** [comment]
You could recreate that quite easily by making some custom rpcs in lua or typescript and calling them, of course thats a lot of overhead you will likely want to avoid :)

**Comment by zyro** [comment]
WASM support is being tracked on the [main Nakama repo](https://github.com/heroiclabs/nakama), keep an eye there for updates. :+1:
