### ISSUE TITLE
Typescript: Error create tournament?

### ISSUE THREAD

**Issue by nguyenkhoa222** [heroiclabs/nakama-common#46]
I tried to create a simple default tournament but it didn't work. Then I have to take all codes from your example from docs but it turn into error too. It logged out nothing but error map[]

![Untitled](https://user-images.githubusercontent.com/90238881/140523584-cdf5a56b-715d-45f2-b6e8-d649ac9d425a.png)

Is there something wrong with your example, my code, or you guys hide some tricks behind the example? Or this is a bug then i have to wait? And by the way, other features are running fine.

**Comment by Ahmadrezadl** [comment]
I have the same issue
I removed try and catch and got this error:
"duration must be > 0"

any solution? 

`function rpcNewTournament(ctx: nkruntime.Context, logger: nkruntime.Logger, nk: nkruntime.Nakama, payload: string){
    logger.info('New tournament rpc called with %s', payload)
    let data = JSON.parse(payload)
    let tournamentID = data.tournamentID;
    let authoritative = data.authoritative;
    let sortOrder = data.sortOrder;
    let operator = data.operator;
    let duration = data.duration;
    let resetSchedule = data.resetSchedule;
    let metadata = data.metadata;
    let title = data.title;
    let description = data.description;
    let category = data.category;
    let startTime = data.startTime;
    let endTime = data.endTime;
    let maxSize = data.maxSize;
    let maxNumScore = data.maxNumScore;
    let joinRequired = data.joinRequired;

    nk.tournamentCreate(
        tournamentID,
        authoritative,
        sortOrder,
        operator,
        duration,
        resetSchedule,
        metadata,
        title,
        description,
        category,
        startTime,
        endTime,
        maxSize,
        maxNumScore,
        joinRequired
    );
    return JSON.stringify({success : true})
}

`

**Comment by novabyte** [comment]
@Ahmadrezadl what version of Nakama server do you use?

**Comment by Ahmadrezadl** [comment]
@novabyte Latest version (3.4.0)

**Comment by Ahmadrezadl** [comment]
@novabyte oh sorry I got it (i used tutorial and think 3.4 is the last version) , I updated nakama and it works now :) 
sorry for the wrong comment and issue :)

**Comment by novabyte** [comment]
No worries. Thanks for following up @Ahmadrezadl.
