### ISSUE TITLE
[TS] Feature request: allow the user to specify the state type for the Authoritative Multiplayer matches

### ISSUE THREAD

**Issue by bananu7** [heroiclabs/nakama-common#52]
Right now, the type for the state is:
```
    export interface MatchState {
        [key: string]: any;
    }
```
It would be great if this was customizable by the user. This would require adding making all the handlers generic accepting that type. It should be easy to make sure that a set of all handlers is coherent, because they're all passed together to `registerMatch`, which could simply fill in that type when typechecking.

To maintain backwards compatibility, I think it could be possible to leave this type in and make it the default value for the generic.

**Comment by sesposito** [comment]
Resolved by #53
