### ISSUE TITLE
[TS] Fix wrong binary array data declaration

### ISSUE THREAD

**Issue by formatCvt** [heroiclabs/nakama-common#66]
Declared `Uint8Array` - https://github.com/formatCvt/nakama-common/blob/master/index.d.ts#L244 (and other places)
Expected `ArrayBuffer` - https://github.com/heroiclabs/nakama/blob/4290fa76c46d28b51a3856c55f999c76215be453/server/runtime_javascript_match_core.go#L567 (and other places)
We should replace **Uint8Array** with **ArrayBuffer**

**Comment by formatCvt** [comment]
`ArrayBuffer` is more flexible way to work with binary data rather than `Uint8Array`

**Comment by zyro** [comment]
Changes merged and should be resolved with the upcoming release. 👍
