### ISSUE TITLE
[BUG] registerAfterDeleteNotifications

### ISSUE THREAD

**Issue by smhmayboudi** [heroiclabs/nakama-common#70]
Hello, I am receiving this error after the registration.

`initializer.registerAfterDeleteNotifications(afterDeleteNotifications);`

`nakama  | {"level":"error","ts":"2022-05-06T08:02:23.102Z","caller":"server/runtime_javascript.go:1524","msg":"Failed to eval JavaScript modules.","error":"TypeError: Object has no member 'registerAfterDeleteNotifications'\n\tat InitModule (index.js:365:49(107))\n\tat native\n"}`

Should i change the name or it should be remove from the project?

**Comment by zyro** [comment]
The correct function is `initializer.registerAfterDeleteNotification` (no `s` at the end). Did you grab it from documentation? If so please let us know where and we'll fix it. 👍

**Comment by smhmayboudi** [comment]
Thanks, please consider `registerBeforeDeleteNotifications` as well.

**Comment by zyro** [comment]
Fixed and will be part of the next release.
