### ISSUE TITLE
[GO] fix the response result for the WalletUpdate function

### ISSUE THREAD

**Issue by smhmayboudi** [heroiclabs/nakama-common#75]
I think this line should be changed.
https://github.com/heroiclabs/nakama-common/blob/036a5bde6b149019e8c1d2716f51ecfa8e36e686/runtime/runtime.go#L995
```
WalletUpdate(ctx context.Context, userID string, changeset map[string]int64, metadata map[string]interface{}, updateLedger bool) (updated map[string]int64, previous map[string]int64, err error)
```
to
```
WalletUpdate(ctx context.Context, userID string, changeset map[string]int64, metadata map[string]interface{}, updateLedger bool) (*WalletUpdateResult, error)
```

**Comment by zyro** [comment]
@smhmayboudi Thanks for the report, but it would help if you added some context. Why should this change be made, and what is the impact?

**Comment by smhmayboudi** [comment]
I think it becomes more readable like the following line after it:
https://github.com/heroiclabs/nakama-common/blob/036a5bde6b149019e8c1d2716f51ecfa8e36e686/runtime/runtime.go#L996
```
WalletsUpdate(ctx context.Context, updates []*WalletUpdate, updateLedger bool) ([]*WalletUpdateResult, error)
```

**Comment by zyro** [comment]
I think you're right and it is more readable, but not enough to be worth breaking backwards compatibility. We'll have to revisit this for Nakama 4.x. 👍
