### ISSUE TITLE
[GO] fix some error messages

### ISSUE THREAD

**Issue by smhmayboudi** [heroiclabs/nakama-common#77]
There are some errors:

error strings should not be capitalizedST1005
error strings should not end with punctuation or newlinesST1005

```
ErrStorageRejectedVersion    = errors.New("Storage write rejected - version check failed.")
ErrStorageRejectedPermission = errors.New("Storage write rejected - permission denied.")
```
error strings should not be capitalizedST1005
```
ErrInvalidChannelTarget = errors.New("Invalid channel target")
ErrInvalidChannelType   = errors.New("Invalid channel type")
```

**Comment by zyro** [comment]
Correct, those errors should not have been capitalised in the first place. That said I think this kind of backwards-incompatible (errors may flow down to clients) stylistic-only change must wait until Nakama 4.x.
