### ISSUE TITLE
[TS] base64UrlEncode vs base64Encode

### ISSUE THREAD

**Issue by ansf** [heroiclabs/nakama-common#92]
I was checking the new release 3.13.1 with runtime 1.24.0 to see if #88 is now fixed.

My test code still is:

`nk.base64UrlEncode(nk.hmacSha256Hash('testpayload', 'testsecret'), false)`

I noticed two things:

1. Only `base64Encode` now accepts a `string | ArrayBuffer` while `base64UrlEncode` still only accepts `string`.
2. When looking at the implementation of `base64encode` and `base64UrlEncode` it looks like both use url-encoding internally.

Side note: it would be nice to have jwt verification built in (as we also do have `jwtGenerate`)

**Comment by zyro** [comment]
Both of these should be fixed on master, and will be part of the next release. Please open a new issue if you notice any more discrepancies. :+1:
