### ISSUE TITLE
nkruntime.accountExportId returns a Uint8Array instead of a string

### ISSUE THREAD

**Issue by antonstefer** [heroiclabs/nakama-common#94]
Nakama image: heroiclabs/nakama-enterprise:3.13.1-r1-mc
Nakama runtime version: 1.24.0

The [documentation](https://heroiclabs.com/docs/nakama/server-framework/typescript-runtime/function-reference/#accountExportId) and the interface clearly states that a string would be returned. Instead a Uint8Array is returned.

**Comment by zyro** [comment]
Fixed on master and will be part of the next release. 👍
