### ISSUE TITLE
[TS] Problem with base64UrlDecode (wrong length)

### ISSUE THREAD

**Issue by MonsterArtur1** [heroiclabs/nakama-common#95]
hi, 
First of all: I've built the current source code, so I have the latest changes regarding Base64.

I have string I wish to base64 decode. "D-piPuEUcFN8I_ZlwW0BVChQvWG446bwmFTMlWXTZ44="
When I use TypeScript implementation result string has 31 chars length. 
`nk.base64UrlDecode(s).length==31`
When I use (https://go.dev/play/) and type the same code as in nakama runtime, result string is 32 chars length
`len(base64.URLEncoding.DecodeString(s))==32`

**Comment by zyro** [comment]
Fixed on master and will be part of the next release. 👍
